### ISSUE TITLE
Find a good Flutter-boilerplate / getting started

### ISSUE THREAD

**Issue by naftis** [rareagency/event-app-showcase#1]
Hyvä boilerplate olisi mahdollisimman lähellä lopullista toteutusta. Mielellään myös suht nätti, mutta tyylejä voi hioa lopuksi.

Tärkeimmät ominaisuudet (näistä voi kirjata tikettejä myöhemmin):
* Feed
* Profiili (profiilikuvan vaihto)
* Kirjautuminen (esim. GAuth, tai perus sähköposti tai kutsukoodi)
* Aikataulusivu / konferenssityylinen sivu

**Comment by eioo** [comment]
Sampleja ja sekalaisia resursseja:
* https://itsallwidgets.com/
* https://github.com/flutter/samples/blob/master/INDEX.md
* https://fluttersamples.com/
* https://www.flutterbyexample.com/
* https://github.com/nisrulz/flutter-examples

**Comment by naftis** [comment]
Flutter apparently has good support for building top bar, bottom bar, etc, so decided to make this fully custom for our needs.
