### ISSUE TITLE
Pystytä Postgraphile + Postgres boilerplate

### ISSUE THREAD

**Issue by naftis** [rareagency/event-app-showcase#2]
Huomioitavaa:
* Migraatiot (Knex?, tuttu ja turvallinen. node-pg-migrate muistaakseni myös erittäin pätevä)
* Tietokantarakennetta ei tarvitse miettiä tämän tiketin puitteissa

**Comment by eioo** [comment]
Löytyi tällainen työkalu: https://github.com/graphile/migrate
Tolla olisi varmaan fiksuin toteuttaa jos käytetään PostGraphile back-endiä.

> complements PostGraphile — works with any application, but PostGraphile's watch mode means that the GraphQL schema is instantly regenerated (without server restart) whenever the database changes

**Comment by naftis** [comment]
@eioo mun mielestä tota vois testata. Migraatiot ei oo kuitenkaan kriittisin osa sovelluksen toimintaa ja jos ne räjähtää niin se ei tapahdu randomisti jossain kohtaa ajoa. Ja ei pitäis olla kauheen iso vaiva siirtyä esim. Knexiin jos räjähdys tapahtuu
